package io.github.graphql.model

import com.fasterxml.jackson.core.`type`.TypeReference

@javax.annotation.Generated(
    value = Array("com.kobylynskyi.graphql.codegen.GraphQLCodegen"),
    date = "2021-03-06T19:48:00+0800"
)
object PullRequestTimelineItemsItemTypeTO extends Enumeration {

    type PullRequestTimelineItemsItemTypeTO = Value

    val ADDED_TO_PROJECT_EVENT: Value = Value("ADDED_TO_PROJECT_EVENT")
    val ASSIGNED_EVENT: Value = Value("ASSIGNED_EVENT")
    val BASE_REF_CHANGED_EVENT: Value = Value("BASE_REF_CHANGED_EVENT")
    val BASE_REF_FORCE_PUSHED_EVENT: Value = Value("BASE_REF_FORCE_PUSHED_EVENT")
    val CLOSED_EVENT: Value = Value("CLOSED_EVENT")
    val COMMENT_DELETED_EVENT: Value = Value("COMMENT_DELETED_EVENT")
    val CONVERTED_NOTE_TO_ISSUE_EVENT: Value = Value("CONVERTED_NOTE_TO_ISSUE_EVENT")
    val CROSS_REFERENCED_EVENT: Value = Value("CROSS_REFERENCED_EVENT")
    val DEMILESTONED_EVENT: Value = Value("DEMILESTONED_EVENT")
    val DEPLOYED_EVENT: Value = Value("DEPLOYED_EVENT")
    val DEPLOYMENT_ENVIRONMENT_CHANGED_EVENT: Value = Value("DEPLOYMENT_ENVIRONMENT_CHANGED_EVENT")
    val HEAD_REF_DELETED_EVENT: Value = Value("HEAD_REF_DELETED_EVENT")
    val HEAD_REF_FORCE_PUSHED_EVENT: Value = Value("HEAD_REF_FORCE_PUSHED_EVENT")
    val HEAD_REF_RESTORED_EVENT: Value = Value("HEAD_REF_RESTORED_EVENT")
    val ISSUE_COMMENT: Value = Value("ISSUE_COMMENT")
    val LABELED_EVENT: Value = Value("LABELED_EVENT")
    val LOCKED_EVENT: Value = Value("LOCKED_EVENT")
    val MARKED_AS_DUPLICATE_EVENT: Value = Value("MARKED_AS_DUPLICATE_EVENT")
    val MENTIONED_EVENT: Value = Value("MENTIONED_EVENT")
    val MERGED_EVENT: Value = Value("MERGED_EVENT")
    val MILESTONED_EVENT: Value = Value("MILESTONED_EVENT")
    val MOVED_COLUMNS_IN_PROJECT_EVENT: Value = Value("MOVED_COLUMNS_IN_PROJECT_EVENT")
    val PINNED_EVENT: Value = Value("PINNED_EVENT")
    val PULL_REQUEST_COMMIT: Value = Value("PULL_REQUEST_COMMIT")
    val PULL_REQUEST_COMMIT_COMMENT_THREAD: Value = Value("PULL_REQUEST_COMMIT_COMMENT_THREAD")
    val PULL_REQUEST_REVIEW: Value = Value("PULL_REQUEST_REVIEW")
    val PULL_REQUEST_REVIEW_THREAD: Value = Value("PULL_REQUEST_REVIEW_THREAD")
    val PULL_REQUEST_REVISION_MARKER: Value = Value("PULL_REQUEST_REVISION_MARKER")
    val READY_FOR_REVIEW_EVENT: Value = Value("READY_FOR_REVIEW_EVENT")
    val REFERENCED_EVENT: Value = Value("REFERENCED_EVENT")
    val REMOVED_FROM_PROJECT_EVENT: Value = Value("REMOVED_FROM_PROJECT_EVENT")
    val RENAMED_TITLE_EVENT: Value = Value("RENAMED_TITLE_EVENT")
    val REOPENED_EVENT: Value = Value("REOPENED_EVENT")
    val REVIEW_DISMISSED_EVENT: Value = Value("REVIEW_DISMISSED_EVENT")
    val REVIEW_REQUESTED_EVENT: Value = Value("REVIEW_REQUESTED_EVENT")
    val REVIEW_REQUEST_REMOVED_EVENT: Value = Value("REVIEW_REQUEST_REMOVED_EVENT")
    val SUBSCRIBED_EVENT: Value = Value("SUBSCRIBED_EVENT")
    val TRANSFERRED_EVENT: Value = Value("TRANSFERRED_EVENT")
    val UNASSIGNED_EVENT: Value = Value("UNASSIGNED_EVENT")
    val UNLABELED_EVENT: Value = Value("UNLABELED_EVENT")
    val UNLOCKED_EVENT: Value = Value("UNLOCKED_EVENT")
    val UNPINNED_EVENT: Value = Value("UNPINNED_EVENT")
    val UNSUBSCRIBED_EVENT: Value = Value("UNSUBSCRIBED_EVENT")
    val USER_BLOCKED_EVENT: Value = Value("USER_BLOCKED_EVENT")

}

class PullRequestTimelineItemsItemTypeTOTypeRefer extends TypeReference[PullRequestTimelineItemsItemTypeTO.type]
