package io.github.graphql.java.model;

@javax.annotation.Generated(
    value = "com.kobylynskyi.graphql.codegen.GraphQLCodegen",
    date = "2021-03-07T19:46:14+0800"
)
public enum IssueTimelineItemsItemTypeTO {

    ADDED_TO_PROJECT_EVENT("ADDED_TO_PROJECT_EVENT"),
    ASSIGNED_EVENT("ASSIGNED_EVENT"),
    CLOSED_EVENT("CLOSED_EVENT"),
    COMMENT_DELETED_EVENT("COMMENT_DELETED_EVENT"),
    CONVERTED_NOTE_TO_ISSUE_EVENT("CONVERTED_NOTE_TO_ISSUE_EVENT"),
    CROSS_REFERENCED_EVENT("CROSS_REFERENCED_EVENT"),
    DEMILESTONED_EVENT("DEMILESTONED_EVENT"),
    ISSUE_COMMENT("ISSUE_COMMENT"),
    LABELED_EVENT("LABELED_EVENT"),
    LOCKED_EVENT("LOCKED_EVENT"),
    MARKED_AS_DUPLICATE_EVENT("MARKED_AS_DUPLICATE_EVENT"),
    MENTIONED_EVENT("MENTIONED_EVENT"),
    MILESTONED_EVENT("MILESTONED_EVENT"),
    MOVED_COLUMNS_IN_PROJECT_EVENT("MOVED_COLUMNS_IN_PROJECT_EVENT"),
    PINNED_EVENT("PINNED_EVENT"),
    REFERENCED_EVENT("REFERENCED_EVENT"),
    REMOVED_FROM_PROJECT_EVENT("REMOVED_FROM_PROJECT_EVENT"),
    RENAMED_TITLE_EVENT("RENAMED_TITLE_EVENT"),
    REOPENED_EVENT("REOPENED_EVENT"),
    SUBSCRIBED_EVENT("SUBSCRIBED_EVENT"),
    TRANSFERRED_EVENT("TRANSFERRED_EVENT"),
    UNASSIGNED_EVENT("UNASSIGNED_EVENT"),
    UNLABELED_EVENT("UNLABELED_EVENT"),
    UNLOCKED_EVENT("UNLOCKED_EVENT"),
    UNPINNED_EVENT("UNPINNED_EVENT"),
    UNSUBSCRIBED_EVENT("UNSUBSCRIBED_EVENT"),
    USER_BLOCKED_EVENT("USER_BLOCKED_EVENT");

    private final String graphqlName;

    private IssueTimelineItemsItemTypeTO(String graphqlName) {
        this.graphqlName = graphqlName;
    }

    @Override
    public String toString() {
        return this.graphqlName;
    }

}
